### ISSUE TITLE
Template creator improvements

### ISSUE THREAD

**Issue by Iranaphor** [Iranaphor/auto_shepherd_whistle_teleop#3]
Implement a better template creation system which will utilise a drawing of bounding boxes on captured frames

**Comment by Iranaphor** [comment]
When using image_view, the rightclick action is to save the frame. We could utilise a subscriber to the spectrogram, and periodic checking for newly saved frames. The frames could be cropped on reading in by the template matcher to the frequency defined in the config file.

Cropping could also be achieved with matplotlib point selection.

**Comment by Iranaphor** [comment]
I like the idea of storing the full spectorgrams and using a config file in the directory to outline the region within the spectrogram for the template, this would allow easier capture, and potentially automation into their detection.

To this effect the file heirarchy would be such like:

```
action/
| frame000.png
| frame001.png
| frame002.png
| frame003.png
| frame004.png 
| templates.yaml
```

The `templates.yaml` would look something like:
```yaml
action: 'right'
bounding_box_colour: [255,0,0]
frequency_search_range:
  min: 50
  max: 5000
sensitivity: 0.5
template_src:
  - name: frame000.png
    box:
        frequency_max: 10
        frequency_min: 20
        time_start: 3
        time_end: 5
  - name: frame001.png
    box:
        frequency_max: 12
        frequency_min: 24
        time_start: 1
        time_end: 3.5
```
